### ISSUE TITLE
在Android的webview中嗅探特性

### ISSUE THREAD

**Issue by lijiahao8898** [givebest/GB-canvas-turntable#1]
您好，首先非常感谢有这么个插件！
在使用的过程中，发现在Android（内核是webbkit）的webview中嗅探特性好像不生效
显示的还是transform，而不是-webkit-transform。

**Comment by givebest** [comment]
`alert(document.createElement('p').style['transitionProperty'])`  打印什么值出来？

**Comment by lijiahao8898** [comment]
打印出来的是“” 。里面什么也没

**Comment by givebest** [comment]
这证明浏览器支持： `transitionProperty`，不支持会返回：`undefined`。
或者：
直接检测 `transform` 是否支持。

**Comment by lijiahao8898** [comment]
我在安卓APP的webview :alert(document.createElement('p').style['transform']); 返回的是： `undefined `;
在安卓APP的微信（X5内核）：alert(document.createElement('p').style['transform']); 返回的是： `  `;

**Comment by givebest** [comment]
你们安卓 WebView 支持 `transitionProperty` 但不支持 `transform`，单独检测 `transform`  并添加前缀吧。

**Comment by lijiahao8898** [comment]
OK。谢谢啦。
